spring:
  application:
    name: catalyst-radar

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

info:
  app:
    name: catalyst-radar
    version: 0.0.1-SNAPSHOT
