package com.catalystradar.domain.event

/**
 * Controlled taxonomy-v1 event types.
 *
 * Every type carries its family so the mapping has a single source of truth
 * and can never drift between layers. New types must follow the process in
 * AGENTS.md: verify no existing type fits, then document direction semantics
 * and scoring behavior with extraction tests.
 */
enum class EventType(val family: EventFamily) {
    // EARNINGS
    EARNINGS_BEAT(EventFamily.EARNINGS),
    EARNINGS_MISS(EventFamily.EARNINGS),
    REVENUE_BEAT(EventFamily.EARNINGS),
    REVENUE_MISS(EventFamily.EARNINGS),
    EPS_BEAT(EventFamily.EARNINGS),
    EPS_MISS(EventFamily.EARNINGS),
    MARGIN_EXPANSION(EventFamily.EARNINGS),
    MARGIN_COMPRESSION(EventFamily.EARNINGS),
    BOOKINGS_ACCELERATION(EventFamily.EARNINGS),
    BOOKINGS_DECELERATION(EventFamily.EARNINGS),
    BACKLOG_GROWTH(EventFamily.EARNINGS),
    BACKLOG_DECLINE(EventFamily.EARNINGS),

    // GUIDANCE
    GUIDANCE_RAISE(EventFamily.GUIDANCE),
    GUIDANCE_CUT(EventFamily.GUIDANCE),
    GUIDANCE_INITIATED(EventFamily.GUIDANCE),
    GUIDANCE_WITHDRAWN(EventFamily.GUIDANCE),
    GUIDANCE_ABOVE_CONSENSUS(EventFamily.GUIDANCE),
    GUIDANCE_BELOW_CONSENSUS(EventFamily.GUIDANCE),
    LONG_TERM_TARGET_RAISED(EventFamily.GUIDANCE),
    LONG_TERM_TARGET_CUT(EventFamily.GUIDANCE),

    // COMMERCIAL
    CONTRACT_WIN(EventFamily.COMMERCIAL),
    CONTRACT_LOSS(EventFamily.COMMERCIAL),
    LARGE_ORDER(EventFamily.COMMERCIAL),
    ORDER_CANCELLATION(EventFamily.COMMERCIAL),
    CUSTOMER_WIN(EventFamily.COMMERCIAL),
    CUSTOMER_LOSS(EventFamily.COMMERCIAL),
    PARTNERSHIP_ANNOUNCED(EventFamily.COMMERCIAL),
    PARTNERSHIP_ENDED(EventFamily.COMMERCIAL),
    PRICING_INCREASE(EventFamily.COMMERCIAL),
    PRICING_DECREASE(EventFamily.COMMERCIAL),
    DEMAND_ACCELERATION(EventFamily.COMMERCIAL),
    DEMAND_DECELERATION(EventFamily.COMMERCIAL),

    // PRODUCT_TECH
    PRODUCT_LAUNCH(EventFamily.PRODUCT_TECH),
    PRODUCT_DELAY(EventFamily.PRODUCT_TECH),
    BREAKTHROUGH(EventFamily.PRODUCT_TECH),
    DEVELOPMENT_MILESTONE(EventFamily.PRODUCT_TECH),
    MAJOR_CUSTOMER_ADOPTION(EventFamily.PRODUCT_TECH),
    CAPACITY_EXPANSION(EventFamily.PRODUCT_TECH),
    CAPACITY_REDUCTION(EventFamily.PRODUCT_TECH),
    PRODUCTION_INCREASE(EventFamily.PRODUCT_TECH),
    PRODUCTION_CUT(EventFamily.PRODUCT_TECH),

    // CORPORATE_ACTION
    ACQUISITION_ANNOUNCED(EventFamily.CORPORATE_ACTION),
    ACQUISITION_COMPLETED(EventFamily.CORPORATE_ACTION),
    TAKEOVER_TARGET(EventFamily.CORPORATE_ACTION),
    TAKEOVER_BID(EventFamily.CORPORATE_ACTION),
    DIVESTITURE(EventFamily.CORPORATE_ACTION),
    SPINOFF(EventFamily.CORPORATE_ACTION),
    STRATEGIC_REVIEW(EventFamily.CORPORATE_ACTION),
    INDEX_INCLUSION(EventFamily.CORPORATE_ACTION),
    INDEX_EXCLUSION(EventFamily.CORPORATE_ACTION),

    // CAPITAL_ALLOCATION
    BUYBACK_ANNOUNCED(EventFamily.CAPITAL_ALLOCATION),
    BUYBACK_INCREASED(EventFamily.CAPITAL_ALLOCATION),
    BUYBACK_SUSPENDED(EventFamily.CAPITAL_ALLOCATION),
    DIVIDEND_INITIATED(EventFamily.CAPITAL_ALLOCATION),
    DIVIDEND_INCREASED(EventFamily.CAPITAL_ALLOCATION),
    DIVIDEND_CUT(EventFamily.CAPITAL_ALLOCATION),
    DIVIDEND_SUSPENDED(EventFamily.CAPITAL_ALLOCATION),
    CAPEX_INCREASE(EventFamily.CAPITAL_ALLOCATION),
    CAPEX_CUT(EventFamily.CAPITAL_ALLOCATION),
    DEBT_ISSUANCE(EventFamily.CAPITAL_ALLOCATION),
    DEBT_REPAYMENT(EventFamily.CAPITAL_ALLOCATION),
    EQUITY_OFFERING(EventFamily.CAPITAL_ALLOCATION),

    // ANALYST
    ANALYST_UPGRADE(EventFamily.ANALYST),
    ANALYST_DOWNGRADE(EventFamily.ANALYST),
    PRICE_TARGET_RAISED(EventFamily.ANALYST),
    PRICE_TARGET_CUT(EventFamily.ANALYST),
    ESTIMATE_REVISION_UP(EventFamily.ANALYST),
    ESTIMATE_REVISION_DOWN(EventFamily.ANALYST),
    COVERAGE_INITIATED(EventFamily.ANALYST),

    // REGULATORY
    APPROVAL_GRANTED(EventFamily.REGULATORY),
    APPROVAL_DENIED(EventFamily.REGULATORY),
    REGULATORY_CLEARANCE(EventFamily.REGULATORY),
    REGULATORY_BLOCK(EventFamily.REGULATORY),
    LICENSE_GRANTED(EventFamily.REGULATORY),
    LICENSE_REVOKED(EventFamily.REGULATORY),
    INVESTIGATION_OPENED(EventFamily.REGULATORY),
    INVESTIGATION_CLOSED(EventFamily.REGULATORY),
    POLICY_TAILWIND(EventFamily.REGULATORY),
    POLICY_HEADWIND(EventFamily.REGULATORY),

    // LEGAL
    LAWSUIT_FILED(EventFamily.LEGAL),
    LAWSUIT_DISMISSED(EventFamily.LEGAL),
    LEGAL_WIN(EventFamily.LEGAL),
    LEGAL_LOSS(EventFamily.LEGAL),
    SETTLEMENT(EventFamily.LEGAL),
    PATENT_WIN(EventFamily.LEGAL),
    PATENT_LOSS(EventFamily.LEGAL),

    // MANAGEMENT_OWNERSHIP
    CEO_APPOINTED(EventFamily.MANAGEMENT_OWNERSHIP),
    CEO_DEPARTURE(EventFamily.MANAGEMENT_OWNERSHIP),
    CFO_APPOINTED(EventFamily.MANAGEMENT_OWNERSHIP),
    CFO_DEPARTURE(EventFamily.MANAGEMENT_OWNERSHIP),
    FOUNDER_RETURN(EventFamily.MANAGEMENT_OWNERSHIP),
    INSIDER_BUY(EventFamily.MANAGEMENT_OWNERSHIP),
    INSIDER_SELL(EventFamily.MANAGEMENT_OWNERSHIP),
    ACTIVIST_POSITION(EventFamily.MANAGEMENT_OWNERSHIP),
    MAJOR_STAKE_INCREASED(EventFamily.MANAGEMENT_OWNERSHIP),
    MAJOR_STAKE_DECREASED(EventFamily.MANAGEMENT_OWNERSHIP),

    // INDUSTRY_EXTERNAL
    PEER_POSITIVE_READTHROUGH(EventFamily.INDUSTRY_EXTERNAL),
    PEER_NEGATIVE_READTHROUGH(EventFamily.INDUSTRY_EXTERNAL),
    CUSTOMER_CONFIRMATION(EventFamily.INDUSTRY_EXTERNAL),
    CUSTOMER_WEAKNESS(EventFamily.INDUSTRY_EXTERNAL),
    SUPPLIER_DISRUPTION(EventFamily.INDUSTRY_EXTERNAL),
    SUPPLIER_IMPROVEMENT(EventFamily.INDUSTRY_EXTERNAL),
    SECTOR_DEMAND_UP(EventFamily.INDUSTRY_EXTERNAL),
    SECTOR_DEMAND_DOWN(EventFamily.INDUSTRY_EXTERNAL),
    COMMODITY_TAILWIND(EventFamily.INDUSTRY_EXTERNAL),
    COMMODITY_HEADWIND(EventFamily.INDUSTRY_EXTERNAL),
}
